---
title: "BabyNames"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
library(babynames)
data(babynames)
##glimpse(babynames)
bella <- babynames %>% filter(name == "Bella" & sex == "F")
babynames %>% select(year, name, n)
Bellas <- babynames %>% filter(name == "Bella" & sex == "F") %>% select(year, name, n)

modified_babynames <- babynames %>% mutate(popular = prop >= 0.01)
```
```{r}
modified_babynames <- rename(modified_babynames, is_popular = popular)
```
```{r}
PopularBabyNames <- modified_babynames %>% filter(is_popular == "TRUE") %>% select(-is_popular)
descpop <- babynames %>% arrange(desc(prop))
#2: To be first in the list, it means that it is the most commonly given baby name throughout the years

mybirth <- PopularBabyNames %>% filter(year == "1999") %>% arrange(desc(prop))
mybirth
```
```{r}
michelle <- PopularBabyNames %>% filter(name == "Michelle") %>% arrange(desc(prop))
michelle
```
```{r}
bigmich <- babynames %>% filter(name =="Michelle") %>% arrange(desc(n))
bigmich
##3. The year could be different becuase more Michelles doesnt mean proportionally high Michelles due to fluctuation in the change in total babies born
```
```{r}
##babynames <- rename(babynames, num_births = n)
babynames
```

```{r}
Bella <- babynames %>% filter(name == "Bella" & sex == "F")
Bella %>% summarize(num_rows = n(), peak_number = max(num_births), peak_year = year[which.max(num_births)])
##7 It tells us the total number of rows in the data set we are working with. In this case, num_rows tells us that there are 136 rows of data, so 136 different "Bella"" entries.
```
```{r}
myyear <- babynames %>% filter(year == "1999")
myyear %>% summarize(num_rows = n(), peak_number = max(num_births))
myyear
```
```{r}
popmich <- babynames %>% filter(name == "Michelle")
popmich %>% summarize(num_rows = n(), peak_number = max(num_births), peak_year = year[which.max(num_births)])

```
```{r}
#head(
#  select(
#    arrange(
#      filter(
#        modified_babynames, name == "Colin" & sex == "M"),
#      desc(num_births)),
#    year, num_births),
#  n = 10)

modified_babynames <- rename(modified_babynames, num_births = n)

modified_babynames %>% filter(name == "Colin" & sex == "M") %>% arrange(desc(num_births)) %>% select(year, num_births) %>% head(n = 10)

```
```{r}
michelle <- PopularBabyNames %>% filter(name == "Michelle") %>% arrange(desc(n))
michelle

popmich <- babynames %>% filter(name == "Michelle")
popmich %>% summarize(num_rows = n(), peak_number = max(num_births), peak_year = year[which.max(num_births)])


```
